### PR TITLE
feat: add animation and custom player

### PR DESCRIPTION
**Pull request by AskMP**
Animation and new classes for all the things.

There are event handlers for the various actions as well as certain properties are set to read-only for external scripts.

Please note that the animation will only show if the browser supports navigation.connection and the speed is above 3G. Setting the Kbps of the stream after the initial page load will cause the stream to increase in speed however the gif and the cover art will not.

### CODE REVIEW

**Comment by raisedadead** [comment]
Overall, I think we can merge this.

**Comment by raisedadead** [comment]
Also, I found that on autoplay (page load, no user interaction) the music stops playing the music if I switch tab. On user action this persists.

**Comment by AskMP** [comment]
I know why the autoplay function on page load doesn't change the button... and in all honesty, it shouldn't autoplay to begin with. I have a fix for that already but if you're saying you're losing the playback on another tab, we need to look into that before merging.

**Comment by AskMP** [comment]
While making this next update, should we have a call to action for the "push space or click here" call-out that disappears upon first play to ensure people know to?

**Comment by raisedadead** [comment]
> While making this next update, should we have a call to action for the "push space or click here" call-out that disappears upon first play to ensure people know to?

That would be a nice to have.

**Comment by AskMP** [comment]
Updated the CTA to what the /fcc site is.

**Pull request merged**
